from pyspark import pipelines as dp
from pyspark.sql import functions as F
from pyspark.sql.window import Window

rules = {
    "cnes_not_null": "cnes IS NOT NULL",
    "treated_cnpj_not_0": "treated_cnpj != '00000000000000'",
    "unique_key": "is_unique = 1"
}

@dp.table()
@dp.expect_all_or_fail(rules)
def int_sus_establishments():

    # Comando em SQL selecionando as colunas para a cada prata
    # Removemos todas as colunas completamente vazias usando o notebook check_establishments_null_columns
    # A coluna treated_cnpj faz um tipo de coalesce quando a coluna cpf_cnpj = '00000000000000', considerando a coluna de cnpj da mantenedora

    sqlDF = spark.sql("""
        SELECT 
            cnes::STRING,
            codufmun::STRING,
            cod_cep::STRING,
            cpf_cnpj::STRING,
            pf_pj::STRING,
            niv_dep::STRING,
            cnpj_man::STRING,
            regsaude::STRING,
            distrsan::STRING,
            vinc_sus::STRING,
            tpgestao::STRING,
            esfera_a::STRING,
            atividad::STRING,
            clientel::STRING,
            tp_unid::STRING,
            turno_at::STRING,
            tp_prest::STRING,
            co_banco::STRING,
            co_agenc::STRING,
            c_corren::STRING,
            alvara::STRING,
            MAKE_DATE(LEFT(dt_exped, 4), SUBSTR(dt_exped, 5, 2), RIGHT(dt_exped, 2)) AS dt_exped,
            orgexped::STRING,
            gesprg1e::BOOLEAN,
            gesprg1m::BOOLEAN,
            gesprg2e::BOOLEAN,
            gesprg2m::BOOLEAN,
            gesprg4e::BOOLEAN,
            gesprg4m::BOOLEAN,
            nivate_a::BOOLEAN,
            gesprg3e::BOOLEAN,
            gesprg3m::BOOLEAN,
            gesprg5e::BOOLEAN,
            gesprg5m::BOOLEAN,
            gesprg6e::BOOLEAN,
            gesprg6m::BOOLEAN,
            nivate_h::BOOLEAN,
            qtleitp1::INT,
            qtleitp2::INT,
            qtleitp3::INT,
            leithosp::BOOLEAN,
            qtinst01::INT,
            qtinst02::INT,
            qtinst03::INT,
            qtinst04::INT,
            qtinst05::INT,
            qtinst06::INT,
            qtinst07::INT,
            qtinst08::INT,
            qtinst09::INT,
            qtinst10::INT,
            qtinst11::INT,
            qtinst12::INT,
            qtinst13::INT,
            qtinst14::INT,
            urgemerg::BOOLEAN,
            qtinst15::INT,
            qtinst16::INT,
            qtinst17::INT,
            qtinst18::INT,
            qtinst19::INT,
            qtinst20::INT,
            qtinst21::INT,
            qtinst22::INT,
            qtinst23::INT,
            qtinst24::INT,
            qtinst25::INT,
            qtinst26::INT,
            qtinst27::INT,
            qtinst28::INT,
            qtinst29::INT,
            qtinst30::INT,
            atendamb::BOOLEAN,
            qtinst31::INT,
            qtinst32::INT,
            qtinst33::INT,
            centrcir::BOOLEAN,
            qtinst34::INT,
            qtinst35::INT,
            qtinst36::INT,
            qtinst37::INT,
            centrobs::BOOLEAN,
            qtleit05::INT,
            qtleit06::INT,
            qtleit07::INT,
            qtleit08::INT,
            qtleit09::INT,
            qtleit19::INT,
            qtleit20::INT,
            qtleit21::INT,
            qtleit22::INT,
            qtleit23::INT,
            qtleit32::INT,
            qtleit34::INT,
            qtleit38::INT,
            qtleit39::INT,
            qtleit40::INT,
            centrneo::BOOLEAN,
            atendhos::BOOLEAN,
            serap01p::BOOLEAN,
            serap01t::BOOLEAN,
            serap02p::BOOLEAN,
            serap02t::BOOLEAN,
            serap03p::BOOLEAN,
            serap03t::BOOLEAN,
            serap04p::BOOLEAN,
            serap04t::BOOLEAN,
            serap05p::BOOLEAN,
            serap05t::BOOLEAN,
            serap06p::BOOLEAN,
            serap06t::BOOLEAN,
            serap07p::BOOLEAN,
            serap07t::BOOLEAN,
            serap08p::BOOLEAN,
            serap08t::BOOLEAN,
            serap09p::BOOLEAN,
            serap09t::BOOLEAN,
            serap10p::BOOLEAN,
            serap10t::BOOLEAN,
            serap11p::BOOLEAN,
            serap11t::BOOLEAN,
            serapoio::BOOLEAN,
            res_biol::BOOLEAN,
            res_quim::BOOLEAN,
            res_radi::BOOLEAN,
            res_comu::BOOLEAN,
            coletres::BOOLEAN,
            comiss01::BOOLEAN,
            comiss02::BOOLEAN,
            comiss03::BOOLEAN,
            comiss04::BOOLEAN,
            comiss05::BOOLEAN,
            comiss06::BOOLEAN,
            comiss07::BOOLEAN,
            comiss08::BOOLEAN,
            comiss09::BOOLEAN,
            comiss10::BOOLEAN,
            comiss11::BOOLEAN,
            comiss12::BOOLEAN,
            comissao::BOOLEAN,
            ap01cv01::BOOLEAN,
            ap01cv02::BOOLEAN,
            ap01cv03::BOOLEAN,
            ap01cv04::BOOLEAN,
            ap01cv05::BOOLEAN,
            ap01cv06::BOOLEAN,
            ap01cv07::BOOLEAN,
            ap02cv01::BOOLEAN,
            ap02cv02::BOOLEAN,
            ap02cv03::BOOLEAN,
            ap02cv04::BOOLEAN,
            ap02cv05::BOOLEAN,
            ap02cv06::BOOLEAN,
            ap02cv07::BOOLEAN,
            ap03cv01::BOOLEAN,
            ap03cv02::BOOLEAN,
            ap03cv03::BOOLEAN,
            ap03cv04::BOOLEAN,
            ap03cv05::BOOLEAN,
            ap03cv06::BOOLEAN,
            ap03cv07::BOOLEAN,
            ap04cv01::BOOLEAN,
            ap04cv02::BOOLEAN,
            ap04cv03::BOOLEAN,
            ap04cv04::BOOLEAN,
            ap04cv05::BOOLEAN,
            ap04cv06::BOOLEAN,
            ap04cv07::BOOLEAN,
            ap05cv01::BOOLEAN,
            ap05cv02::BOOLEAN,
            ap05cv03::BOOLEAN,
            ap05cv04::BOOLEAN,
            ap05cv05::BOOLEAN,
            ap05cv06::BOOLEAN,
            ap05cv07::BOOLEAN,
            ap06cv01::BOOLEAN,
            ap06cv02::BOOLEAN,
            ap06cv03::BOOLEAN,
            ap06cv04::BOOLEAN,
            ap06cv05::BOOLEAN,
            ap06cv06::BOOLEAN,
            ap06cv07::BOOLEAN,
            ap07cv01::BOOLEAN,
            ap07cv02::BOOLEAN,
            ap07cv03::BOOLEAN,
            ap07cv04::BOOLEAN,
            ap07cv05::BOOLEAN,
            ap07cv06::BOOLEAN,
            ap07cv07::BOOLEAN,
            atend_pr::BOOLEAN,
            MAKE_DATE(LEFT(dt_atual, 4), SUBSTR(dt_atual, 5, 2), RIGHT(dt_atual, 2)) AS dt_atual,
            MAKE_DATE(LEFT(competen, 4), SUBSTR(competen, 5, 2), RIGHT(competen, 2)) AS competen,
            nat_jur::STRING,
            file_name::STRING,
            CASE 
                WHEN cpf_cnpj = '00000000000000' THEN cnpj_man 
                ELSE cpf_cnpj 
            END::STRING AS treated_cnpj
        FROM stg_sus_establishments
    """)
    
    # Faz um rownumber por cnes, treated_cnpj e file_name
    window_spec = Window.partitionBy("cnes", "treated_cnpj", "file_name").orderBy(F.lit(1))
    
    # Se houver 2 linhas iguais, a primeira recebe 1 e a segunda recebe 2 
    # A presença de uma linha com valor <> 1 vai falhar a regra de is_unique
    return sqlDF.withColumn("is_unique", F.row_number().over(window_spec))
    